# Generated by Django 4.2.14 on 2024-08-19 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_category_status'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movienews',
            name='actor',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 1}, related_name='newsactors', to='common.actor'),
        ),
        migrations.AlterField(
            model_name='movienews',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movienews', related_query_name='moviesnews', to='common.category'),
        ),
        migrations.AlterField(
            model_name='movienews',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.country'),
        ),
        migrations.AlterField(
            model_name='movienews',
            name='regisseurs',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 1}, related_name='newsregisseurs', to='common.actor'),
        ),
        migrations.AlterField(
            model_name='movienews',
            name='trailer',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
