# Generated by Django 4.2.14 on 2024-08-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_award_name_alter_country_name'),
        ('news', '0002_alter_movienews_actor_alter_movienews_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movienews',
            name='actor',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 0}, related_name='newsactors', to='common.actor'),
        ),
    ]
