# Generated by Django 4.2.14 on 2024-08-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=225, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='verifyemail',
            name='code',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Verify code'),
        ),
        migrations.AlterField(
            model_name='verifyemail',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=225, null=True, unique=True),
        ),
    ]
