# Generated by Django 4.2.14 on 2024-08-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'Actor'), (1, 'Regisseur')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Movie'), (1, 'News')], default=0, null=True),
        ),
    ]
