# Generated by Django 4.2.14 on 2024-08-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_genre_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='slug',
        ),
    ]
