# Generated by Django 4.2.14 on 2024-08-19 09:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(blank=True, max_length=225, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
